volumes:
  nppd-db-data:
  nppd-frontend-node_modules:
  nppd-backend-node_modules:

services:
  nppd-db:
    image: postgres:17
    container_name: nppd-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Europe/Paris"
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - nppd-db-data:/var/lib/postgresql/data

  nppd-frontend:
    container_name: nppd-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/dev.Dockerfile
    restart: unless-stopped
    depends_on:
      - nppd-db
    environment:
      TZ: "Europe/Paris"
    ports:
      - "${FRONTEND_PORT_EXTERNAL}:3000"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src:rw
      - ./apps/frontend/public:/app/apps/frontend/public:rw
      - nppd-frontend-node_modules:/app/node_modules

  nppd-backend:
    container_name: nppd-backend
    build:
      context: .
      dockerfile: ./apps/backend/dev.Dockerfile
    restart: unless-stopped
    depends_on:
      - nppd-db
    environment:
      TZ: "Europe/Paris"
    ports:
      - "${BACKEND_PORT_EXTERNAL}:3000"
    volumes:
      - ./apps/backend/src:/app/apps/backend/src:rw
      - nppd-backend-node_modules:/app/node_modules
